### ISSUE TITLE
No inicia el juego 

### ISSUE THREAD

**Issue by lJ4V1l** [SadlyThresh/DDBS_ESP#1]
![Captura de pantalla (133)](https://user-images.githubusercontent.com/71604292/93717589-66d3fd80-fb3c-11ea-82af-f1685c2e52b2.png)
Seguí todos los pasos del video para realizar la instalación  del mod y el parche al pie de la letra. 
Aun así sale ese error apenas doy click en el juego para inciarlo.

**Comment by SadlyThresh** [comment]
¡Hola!, gracias por ponerte en contacto. 

Ese es un error del archivo poemwords que ocurre en ciertos equipos, la solución es que descargues el poemwords nuevo, y pasarlo a la carpeta "tl" -> "Spanish" y sustituyas el viejo, con eso, abrelo 1 o 2 veces hasta que cargue el juego, en unas horas estará actualizado en la página de descargas.
[poemwords.txt](https://github.com/SadlyThresh/DDBS_ESP/files/5252276/poemwords.txt)
