### ISSUE TITLE
tengo un error cuando quiero ejecutar el juego me sale esto 

### ISSUE THREAD

**Issue by juandialba** [SadlyThresh/DDBS_ESP#10]
![image](https://user-images.githubusercontent.com/74660261/99530522-6951a880-296f-11eb-96c1-e181ac446800.png)

**Comment by SadlyThresh** [comment]
¡Hola!, eso es extraño.

¿Instalaste el Mod y parche correctamente?

Primero el DDLC, luego el Mod de Blue Skies en inglés y encima nuestro parche en Español.

(Nuestro parche no incluye el Mod, así que si lo ejecutas solo con el parche saldrá errores)
