### ISSUE TITLE
No me deja iniciar la traducción

### ISSUE THREAD

**Issue by Bulko117** [SadlyThresh/DDBS_ESP#11]
Puedo iniciar el mod cuando no esta traducido pero cuando instalo la traducción no me deja iniciar el juego, esto es lo que me sale en el traceback: 
I'm sorry, but an uncaught exception occurred.
While running game code:
  File "game/definitions.rpy", line 4459, in script
Exception: Possible infinite loop.

Lo instalo exactamente como en el video que subieron a su canal de Youtube pero no me deja, espero que me den una solución porque realmente quiero jugar el mod. Gracias

**Comment by SadlyThresh** [comment]
¡Hola!, la solución es muy sencilla, sólo inicia varias veces el Mod con el parche hasta que funcione, luego no tendrás ningún problema para iniciar el juego.
