### ISSUE TITLE
No habre el juego al parchearlo al español

### ISSUE THREAD

**Issue by AlexSmash138** [SadlyThresh/DDBS_ESP#12]
El juego me habré correctamente (sin el parche) sin ningún tipo de problema, pero cuando instalo el parche el juego tarda mucho en abrir, y cuando abre sale este error (tanto en la version de Steam como la original)
![0TUOMJRfq6](https://user-images.githubusercontent.com/50784052/102023605-2531a800-3d63-11eb-9924-696305063f88.png)
![explorer_0HiEnmItFQ](https://user-images.githubusercontent.com/50784052/102023610-2c58b600-3d63-11eb-97cd-5aab04a79f71.png)

E intentado borrar los datos del juego pero no funciona, espero que puedan ayudarme.

**Comment by SadlyThresh** [comment]
¡Hola!, la solución a ese error es simplemente abrir el juego varias veces, está generando archivos de traducción, entonces abre el juego varias veces con el parche instalado hasta que inicie, luego iniciará normal
