### ISSUE TITLE
Problemas con el parche

### ISSUE THREAD

**Issue by ImPixel64** [SadlyThresh/DDBS_ESP#17]
Queri aprobar el mod asi que segui los pasos del video tod bien hasta que vi que el parche estaba en Script en lugar de copiar una carpeta game, entonces supuse que el parche ya era mas sencillo de instalar con tan solo copiar y pegar ese archivo pero al abrir el juego no vi ningun cambio

**Comment by SadlyThresh** [comment]
El vídeo fue hecho para una versión antigua del parche, ya no es relevante, la última versión trae el juego completo en Español, todo lo que debes hacer, es descargar el Doki Doki desde [aquí](https://ddlc.moe/).

Luego descargar el Blue Skies en español desde [aquí](https://github.com/SadlyThresh/DDBS_ESP/releases/download/1.0.5/DokiDokiBlueSkies1.0.5.zip) y copiarlo dentro de la carpeta Game del Doki Doki.

Borra el archivo "firstrun" e inicia el juego.
