### ISSUE TITLE
no inicia

### ISSUE THREAD

**Issue by cryro529** [SadlyThresh/DDBS_ESP#3]
buenos dias mi problema con el mod de DDLC blue skies es que cuando lo intento iniciar no abre repetidas veces le clique incluso lo inicie como administrador pero me tira un bloc de notas que dice lo siguiente
![Captura de pantalla (106)](https://user-images.githubusercontent.com/72321964/95002341-512cf200-0598-11eb-87b9-5b0bead565cf.png)

les agradezco que me respondan lo mas pronto posible ya que me interesa su mod del juego muchas gracias

**Comment by SadlyThresh** [comment]
¡Hola!, gracias por ponerte en contacto.

Es un error que ocurre cuando tu equipo tarda mucho en cargar los archivos. 

¿El juego te inicia correctamente sin el parche?, es decir, ¿en inglés?

De no ser así, lastimosamente nosotros sólo solucionamos problemas del parche, no del mod en sí mismo.

En cambio, si tú error ocurre sólo con el parche, por favor únete a nuestro Discord dónde te podremos dar una asistencia más directa en este [link](https://discord.gg/dSaesy)

**Comment by cryro529** [comment]
si me carga el juego sin el parche a la primera entonces que hago?
