### ISSUE TITLE
Playing in Ubuntu linux 16.04 LTS

### ISSUE THREAD

**Issue by Antonio763** [SadlyThresh/DDBS_ESP#4]
Hi¡ i am sad to say yall that the game does not work if i install the translate in my game, desgracely i did all steps and when i will enter the game, it does not run :( can we do anything? Or then do a android port. It does not look so hard, alr i will wait for it i love this game and i cant wait for the answer (T-T)

**Comment by Antonio763** [comment]
Traducción: 
Hola, me entristece decirles a todos que el juego no funciona si instalo el traductor en mi juego, lamentablemente hice todos los pasos y cuando entro en el juego, no se ejecuta :( ¿podemos hacer algo? un port para  Android. No parece tan difícil, también lo esperaré, me encanta este juego y no puedo esperar la respuesta (T-T)

**Comment by Antonio763** [comment]
LOL man, i did it, i published it, wanna help?

**Comment by Antonio763** [comment]
THX bro i will send the things in terminal, and can u send me all your linux RAM, SSD, And specially which version is?

**Comment by SadlyThresh** [comment]
It is not really important the specifications of the computer, if the game runs in English, it will run in Spanish, just change the dialogues, don't add anything else.


So send me a screenshot of the error preventing you from opening the game, The file is usually a "traceback" that you find in the game folder.

**Comment by Antonio763** [comment]
![1.jpg](https://user-images.githubusercontent.com/62559557/95664171-9dc97d80-0b02-11eb-9f40-14b9d7fdf565.jpg)

![2.jpg](https://user-images.githubusercontent.com/62559557/95664176-a5892200-0b02-11eb-976e-e8c1f2ea5d86.jpg)

![2-second part.jpg](https://user-images.githubusercontent.com/62559557/95664181-ade15d00-0b02-11eb-952b-a2d4035c9ae1.jpg)

![3.jpg](https://user-images.githubusercontent.com/62559557/95664183-b2a61100-0b02-11eb-8c7c-25d9a91e39c0.jpg)

**Comment by Antonio763** [comment]
If u need i translate all the txt I have written what appears to me when open the sh and open the file exe, written in a txt file and the images show the screen from top to bottom, the part which says "al abrir el sh" is all text that appear when i run sh, and "al abrir el archivo exe" when i run the file exe, "Mi computadora"=My computer.

**Comment by SadlyThresh** [comment]
Vale, leí el archivo y es un error bastante inusual, asumo que estás usando Wine para abrir el juego, si es así no lo hagas, el archivo .sh es nativo de Linux, pero si el error te da de igual forma, entonces...

-Intenta iniciar el exe, (Si, con Wine) varias veces (Hasta 5-6 si son necesarias), esto convertirá los archivos RPY del parche en RPYC y el juego iniciará, (Si tú computadora no es tan veloz te sale ese error de "infinite loop")

-Si ejecutas el juego como root, no lo hagas, no es recomendable. 

-Verifica que al iniciar, el juego va creando dichos archivos RPYC en la carpeta del juego, son muchos archivos que hace la conversión en "tl/Spanish", en última instancia podría pasarte un Zip con los archivos ya convertidos.

-Si ninguna de las soluciones anteriores funciona, no puedo solucionarte este inconveniente porque es un tema de tu OS acompañado de la capacidad de tu computador de hacer el procesamiento.

**Comment by Antonio763** [comment]
Vale bro intentaré entonces eso pero de igual manera me encantaría que me enviaras el juego con los archivos ya creados si no es problema para ti.

**Comment by Antonio763** [comment]
En Github veo que no se puede enviar archivos, en cualquier caso mi Gmail es blackmatoxj@gmail.com

**Comment by Antonio763** [comment]
Y por cierto me saltó eso de infinite loop

**Comment by Antonio763** [comment]
Lo logreee!!! Gracias bro SOS un capo hermano 😁😁😁
