### ISSUE TITLE
Error en la traducción

### ISSUE THREAD

**Issue by Solembum041** [SadlyThresh/DDBS_ESP#5]
Hola, verán cuando llega la hora de compartir los problemas todo el texto me aparece en ingles y se reanuda la traducción una vez termino de compartir poemas. También toda la situación del evento de Halloween me apareció en ingles. Estaría muy agradecido si me indican como arreglar ese problemas.

Muchas gracias por el esfuerzo que hacen y por traducir este mod.

**Comment by SadlyThresh** [comment]
¡Hola!, vale eso es muy extraño~ 

Pero verifica estas preguntas: 

-¿Tienes la última versión de parche al Español? (1.1)

-¿Tienes la última versión del Blue Skies en inglés?

Recuerda que la traducción no funcionará del todo bien si estás jugando la versión 1.0.4 o 1.0.3 de Blue Skies.

Este parche fue hecho para la versión 1.0.5, puedes verificar la versión del Mod en la pantalla de inicio, en la parte inferior.

**Comment by Solembum041** [comment]
No se cual haya sido el problema, pero decidí desinstalar e instalar nuevamente y funciono, los errores se corrigieron, seguramente copie mal alguna carpeta y eso produjo el error.

De antemano una disculpa y gracias por responder.
