### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DavidNavarro27** [SadlyThresh/DDBS_ESP#7]
Hola le mando este mensaje para que me ayude con un error que e tenido al instalar el parche de doki doki blue skies Español, el juego al ingles me funciona bien pero la traduccion no el video que subieron de como instalarlo paso a paso lo hice pero no me a funcionado ayuda por favor. (Lamento no dar una imagen solo dice Im sorry but an uncaught exception ocurred

**Comment by SadlyThresh** [comment]
¡Hola!, Sería bueno si al menos pudieras enviar el archivo "Traceback.txt" que se genera cuando te pasa el error, se encuentra dentro de la carpeta del juego

**Comment by cipriano115** [comment]
Me pasa lo mismo :(
El juego por defecto (sin el parche) si me inicia pero con el parche en español no.
Lo he hecho todo justo como dice el video pero el juego no me inicia.
Les pasare el archivo Traceback.txt espero puedan ayudarme.
[traceback.txt](https://github.com/SadlyThresh/DDBS_ESP/files/5467462/traceback.txt)
