### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cipriano115** [SadlyThresh/DDBS_ESP#8]
El juego me anda bien sin el parche.
Pero si le pongo el parche no me inicia :(
Espero puedan ayudarme.
Les pasare el archivo traceback.txt
[traceback.txt](https://github.com/SadlyThresh/DDBS_ESP/files/5467488/traceback.txt)

**Comment by SadlyThresh** [comment]
Ese error ocurre básicamente porque tu computador demora en cargar todos los archivos del parche, la solución es muy simple, debes abrir el juego varias veces hasta que inicie, incluso 5 o más veces si es necesario con el parche instalado claro.
