### ISSUE TITLE
Hola.

### ISSUE THREAD

**Issue by Santiago13244** [SadlyThresh/DDBS_ESP#9]
Oye Tengo un error al descargar la traduccion de doki doki blue skies me sale esto: 

 
![Captura](https://user-images.githubusercontent.com/73805762/97824034-93317c80-1c99-11eb-84e2-2eb9ac9369cf.PNG)

Espero que me diga como arreglarlo gracias

**Comment by SadlyThresh** [comment]
Este error se soluciona abriendo un par de veces más el juego, depende del equipo pero solo abre el juego varias veces con el parche, ¡hasta que inicie correctamente!
